[package]
name = "gitzeug"
version = "0.4.0"
edition = "2024"
description = "A CLI toolkit for streamlined git operations."


[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive", "cargo"] }
tempfile = "3.20.0"
